
on:
  workflow_call:
    inputs:
      platform:
        type: string
        required: true
      runner:
        type: string
        required: true
      container:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true
      COSIGN_PASSWORD:
        required: true
      COSIGN_PRIVATE_KEY:
        required: true

################################################################################

jobs:
  build_push:
    name: Build and Push
    runs-on: ${{ inputs.runner }}
    steps:

    #===========================================================================
    - name: Checkout
      uses: actions/checkout@v4

    #===========================================================================
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    #===========================================================================
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    #===========================================================================
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    #===========================================================================
    - name: Setup Cosign
      uses: sigstore/cosign-installer@v4.0.0
      with:
        cosign-release: v3.0.4

    #===========================================================================
    - name: Build and Push by Digest
      id: build
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.platform }}
        file: ${{ inputs.container }}/Containerfile
        context: ${{ inputs.container }}/
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.container }}
          quay.io/${{ github.repository_owner }}/${{ inputs.container }}
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
        sbom: false
        provenance: false

    #===========================================================================
    - name: Export Sanitized Platform
      id: platform
      run: |
        platform=${{ inputs.platform }}
        echo "platform=${platform//\//-}" >> $GITHUB_OUTPUT

    #===========================================================================
    - name: Generate GHCR SBOM
      uses: anchore/sbom-action@v0
      with:
        image: "ghcr.io/${{ github.repository_owner }}/${{ inputs.container }}@${{ steps.build.outputs.digest }}"
        format: spdx-json
        output-file: ${{ runner.temp }}/sbom-ghcr-${{ steps.platform.outputs.platform }}.spdx.json
        upload-artifact: false
    
    #===========================================================================
    - name: Generate GHCR Provenance
      uses: actions/attest-build-provenance@v3
      id: attest-ghcr
      with:
        subject-name: ghcr.io/${{ github.repository_owner }}/${{ inputs.container }}
        subject-digest: ${{ steps.build.outputs.digest }}
        push-to-registry: false

    #===========================================================================
    - name: Generate Quay SBOM
      uses: anchore/sbom-action@v0
      with:
        image: "quay.io/${{ github.repository_owner }}/${{ inputs.container }}@${{ steps.build.outputs.digest }}"
        format: spdx-json
        output-file: ${{ runner.temp }}/sbom-quay-${{ steps.platform.outputs.platform }}.spdx.json
        upload-artifact: false

    #===========================================================================
    - name: Generate Quay Provenance
      uses: actions/attest-build-provenance@v3
      id: attest-quay
      with:
        subject-name: quay.io/${{ github.repository_owner }}/${{ inputs.container }}
        subject-digest: ${{ steps.build.outputs.digest }}
        push-to-registry: false

    #===========================================================================
    - name: Attest and Sign Platform Manifest with Cosign
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        GHCR_USER: ${{ github.actor }}
        GHCR_TOKEN: ${{ github.token }}
        QUAY_USER: ${{ secrets.QUAY_USERNAME }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: |
        ghcr="ghcr.io/${{ github.repository_owner }}/${{ inputs.container }}@${{ steps.build.outputs.digest }}"
        ghcr_prov="${{ steps.attest-ghcr.outputs.bundle-path }}"
        quay="quay.io/${{ github.repository_owner }}/${{ inputs.container }}@${{ steps.build.outputs.digest }}"
        quay_prov="${{ steps.attest-quay.outputs.bundle-path }}"
        cosign login ghcr.io -u "$GHCR_USER" -p "$GHCR_TOKEN"
        cosign login quay.io -u "$QUAY_USER" -p "$QUAY_TOKEN"
        for reg in ghcr quay; do
          cosign clean --force "${!reg}"
          prov_file=${reg}_prov
          cosign attest --yes \
            --key=env://COSIGN_PRIVATE_KEY \
            --type=spdxjson \
            --predicate="${!prov_file}" \
            "${!reg}"
          cosign attest --yes \
            --key=env://COSIGN_PRIVATE_KEY \
            --type=slsaprovenance \
            --predicate="${{ runner.temp }}/provenance-${reg}-${{ steps.platform.outputs.platform }}.json" \
            "${!reg}"
        done
        cosign sign --yes \
          --key=env://COSIGN_PRIVATE_KEY \
          "$ghcr" "$quay"

    #===========================================================================
    - name: Export Digest
      id: digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"

    #===========================================================================
    - name: Upload Digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ steps.platform.outputs.platform }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1

################################################################################
