
on:
  workflow_call:
    inputs:
      platform:
        type: string
        required: true
      runner:
        type: string
        required: true
      container:
        type: string
        required: true
      version:
        type: string
        required: true
      build-args:
        type: string
        required: false
      alt-container-name:
        type: string
        required: false
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true
      COSIGN_PASSWORD:
        required: true
      COSIGN_PRIVATE_KEY:
        required: true

################################################################################

jobs:
  build_push:
    name: Build and Push
    runs-on: ${{ inputs.runner }}
    steps:

    #===========================================================================
    - name: Checkout
      uses: actions/checkout@v4

    #===========================================================================
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    #===========================================================================
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    #===========================================================================
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    #===========================================================================
    - name: Setup Cosign
      uses: sigstore/cosign-installer@v4.0.0
      with:
        cosign-release: v3.0.4

    #===========================================================================
    - name: Build and Push by Digest
      id: build
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.platform }}
        file: ${{ inputs.container }}/Containerfile
        context: ${{ inputs.container }}/
        build-args: ${{ inputs.build-args }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.alt-container-name || inputs.container }}
          quay.io/${{ github.repository_owner }}/${{ inputs.alt-container-name || inputs.container }}
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
        sbom: false
        provenance: false

    #===========================================================================
    - name: Export Sanitized Platform
      id: platform
      run: |
        platform=${{ inputs.platform }}
        echo "platform=${platform//\//-}" >> $GITHUB_OUTPUT

    #===========================================================================
    - name: Export Image References
      id: images
      run: |
        ghcr="ghcr.io/${{ github.repository_owner }}/${{ inputs.alt-container-name || inputs.container }}"
        echo "ghcr=${ghcr}" >> $GITHUB_OUTPUT
        ghcr_digest="${ghcr}@${{ steps.build.outputs.digest }}"
        echo "ghcr_digest=${ghcr_digest}" >> $GITHUB_OUTPUT
        quay="quay.io/${{ github.repository_owner }}/${{ inputs.alt-container-name || inputs.container }}"
        echo "quay=${quay}" >> $GITHUB_OUTPUT
        quay_digest="${quay}@${{ steps.build.outputs.digest }}"
        echo "quay_digest=${quay_digest}" >> $GITHUB_OUTPUT

    #===========================================================================
    - name: Ensure Clean Image
      run: |
        cosign login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
        cosign login quay.io -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_TOKEN }}"
        cosign clean --force "${{ steps.images.outputs.ghcr_digest }}"
        cosign clean --force "${{ steps.images.outputs.quay_digest }}"

    #===========================================================================
    - name: Generate GHCR SBOM
      uses: anchore/sbom-action@v0
      with:
        image: "${{ steps.images.outputs.ghcr_digest }}"
        format: spdx-json
        output-file: ${{ runner.temp }}/sbom-ghcr-${{ steps.platform.outputs.platform }}.spdx.json
        upload-artifact: false

    #===========================================================================
    - name: Attest GHCR SBOM
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      run: |
        cosign login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
        cosign attest --yes \
          --key=env://COSIGN_PRIVATE_KEY \
          --type=spdxjson \
          --predicate="${{ runner.temp }}/sbom-ghcr-${{ steps.platform.outputs.platform }}.spdx.json" \
          "${{ steps.images.outputs.ghcr_digest }}"

    #===========================================================================
    - name: Generate GHCR Provenance
      uses: actions/attest-build-provenance@v3
      id: attest-ghcr
      with:
        subject-name: ${{ steps.images.outputs.ghcr }}
        subject-digest: ${{ steps.build.outputs.digest }}

    #===========================================================================
    - name: Attach GHCR Provenance
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      run: |
        cosign login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
        cosign attach attestation \
          --attestation="${{ steps.attest-ghcr.outputs.bundle-path }}" \
          "${{ steps.images.outputs.ghcr_digest }}"

    #===========================================================================
    - name: Generate Quay SBOM
      uses: anchore/sbom-action@v0
      with:
        image: "${{ steps.images.outputs.quay_digest }}"
        format: spdx-json
        output-file: ${{ runner.temp }}/sbom-quay-${{ steps.platform.outputs.platform }}.spdx.json
        upload-artifact: false

    #===========================================================================
    - name: Attest Quay SBOM
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      run: |
        cosign login quay.io -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_TOKEN }}"
        cosign attest --yes \
          --key=env://COSIGN_PRIVATE_KEY \
          --type=spdxjson \
          --predicate="${{ runner.temp }}/sbom-quay-${{ steps.platform.outputs.platform }}.spdx.json" \
          "${{ steps.images.outputs.quay_digest }}"

    #===========================================================================
    - name: Generate Quay Provenance
      uses: actions/attest-build-provenance@v3
      id: attest-quay
      with:
        subject-name: "${{ steps.images.outputs.quay }}"
        subject-digest: ${{ steps.build.outputs.digest }}

    #===========================================================================
    - name: Attach Quay Provenance
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      run: |
        cosign login quay.io -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_TOKEN }}"
        cosign attach attestation \
          --attestation="${{ steps.attest-quay.outputs.bundle-path }}" \
          "${{ steps.images.outputs.quay_digest }}"

    #===========================================================================
    - name: Attest and Sign Platform Manifest with Cosign
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      run: |
        cosign login ghcr.io -u "${{ github.actor }}" -p "${{ github.token }}"
        cosign login quay.io -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_TOKEN }}"
        cosign sign --yes \
          --key=env://COSIGN_PRIVATE_KEY \
          "${{ steps.images.outputs.ghcr_digest }}" \
          "${{ steps.images.outputs.quay_digest }}"

    #===========================================================================
    - name: Export Digest
      id: digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"

    #===========================================================================
    - name: Upload Digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ steps.platform.outputs.platform }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1

################################################################################
